/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.schoolproject.database.ManagementDataBase;

import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import com.mycompany.schoolproject.database.ExecuteQuesries;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    public registerUser() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel2 = new javax.swing.JLabel();
        Jlabel1 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        resgiter = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        phone_number = new javax.swing.JSpinner();
        name = new javax.swing.JTextField();
        select = new javax.swing.JComboBox<>();
        document = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel2.setText("Nombre");

        Jlabel1.setText("Documento");

        jlabel3.setText("Teléfono");

        jlabel4.setText("Rol usuario");

        jlabel5.setText("contraseña");

        resgiter.setText("Registrar usuario");
        resgiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resgiterActionPerformed(evt);
            }
        });

        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir opción", "estudiante", "profesor" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabel5)
                            .addComponent(Jlabel1)
                            .addComponent(jlabel2)
                            .addComponent(jlabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password)
                            .addComponent(name)
                            .addComponent(select, 0, 160, Short.MAX_VALUE)
                            .addComponent(document, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(resgiter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel1)
                    .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel3)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel4)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel5)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(resgiter)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resgiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgiterActionPerformed
        LinkedHashMap<String, String> data = getDataInterface();
        cleanWidgets();
        if (data.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "vuelva a llenar el formulario");
        }
        else
        {
            new ExecuteQuesries().insertData(
                    "users", 
                    new String[]{"name", "document", "phone_number", "password", "role"}, 
                    new String[]{data.get("name"), data.get("document"), data.get("phone_number"), data.get("password"), data.get("role")}
            );
            JOptionPane.showMessageDialog(null, "Guardado con exito");
            int option = JOptionPane.showConfirmDialog( null, "Desea asignar el horario?");
            if (option == 0)
            {
                registreSchedule schedule = new registreSchedule();
                schedule.openWindow(this, schedule);
                schedule.insertOptions(data.get("role"), data.get("document"), data.get("password"));
                schedule.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_resgiterActionPerformed
    
    public void cleanWidgets()
    {
        phone_number.setValue(0);
        document.setValue(0);
        name.setText("");
        select.setSelectedIndex(0);
        password.setText("");
    }
    
    public LinkedHashMap<String, String> getDataInterface()
    {
        String nameUser = name.getText();
        String roleUser = select.getSelectedItem().toString();
        String numberUser = phone_number.getValue().toString().equals("0") ? "" : phone_number.getValue().toString();
        String documentUser = document.getValue().toString().equals("0") ? "" : document.getValue().toString();
        String passwordUser = password.getText();
        
        LinkedHashMap<String, String> data = new LinkedHashMap<String, String>(){{
            put("name", nameUser.trim() == "" ? null : nameUser);
            put("phone_number", numberUser.trim() == "" ? null : numberUser);
            put("role", roleUser.trim() == "" ? null : roleUser);
            put("document", documentUser.trim() == "" ? null : documentUser);
            put("password", passwordUser.trim() == "" ? null : passwordUser);
        }};
        
        for(String item : data.values())
        {
            if (item == null)
            {
                JOptionPane.showMessageDialog(null, "Se encontro un campo vacio");
                data.clear();
                return data;
            }
        }
        
        if (new ExecuteQuesries().requestDocumentExists(documentUser))
        {
            JOptionPane.showMessageDialog(null, "Ese documento ya existe o no es valido\nCambie ese valor");
            data.clear();
            return data;
        }
        return data;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JSpinner document;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JSpinner phone_number;
    private javax.swing.JButton resgiter;
    private javax.swing.JComboBox<String> select;
    // End of variables declaration//GEN-END:variables
}
